openapi: 3.0.0
info:
  title: Travellico API
  version: 1.0.0
paths:
  /:
    get:
      summary: Main route
      responses:
        '200':
          description: A simple greeting message
  /user:
    get:
      summary: User main route
      responses:
        '200':
          description: A simple greeting message for user
    /info:
      get:
        summary: User information main route
        responses:
          '200':
            description: A simple greeting message for user information
      /exist:
        get:
          summary: Check if user information file exists
          responses:
            '200':
              description: Returns a JSON object with a message indicating whether the user information file exists
      /create:
        get:
          summary: Create a new user information file
          responses:
            '200':
              description: Returns a JSON object with a message indicating the result of the file creation operation
      /add:
        post:
          summary: Add user information to the file
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      type: string
                      description: The user information to add
          responses:
            '200':
              description: Returns a JSON object with a message indicating the result of the add operation
      /data:
        get:
          summary: Get user information from the file
          responses:
            '200':
              description: Returns a JSON object with the user information